language: node_js
sudo: required
serivces: 
  - mongodb
before_script:
  - npm run db
  - sleep 10
  - mongo --eval db
after_script:
  - ps -eaf | grep mongod | grep -v grep | awk '{print $2}' | xargs kill
node_js:
  - "0.12"
  - "iojs"
  - "iojs-v1.0.4" 
